[package]
name = "Sodapop-Reimagined"
version = "0.0.0"
description = "A local modern-looking music player written in Vue + Tauri"
authors = ["crackheadakira"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
anyhow = "1.0.95"
dirs = "6.0.0"
discord-rich-presence = "0.2.5"
dotenvy = "0.15.7"
kira = "0.10.4"
metadata_audio = { path = "./metadata_audio" }
r2d2 = "0.8.10"
r2d2_sqlite = "0.26.0"
raw-window-handle = "0.6.2"
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
specta = "2.0.0-rc.21"
specta-typescript = "0.0.9"
souvlaki = { version = "0.8.0", default-features = false, features = [
    "use_zbus",
] }
tauri = { version = "2.2.5", features = ["protocol-asset"] }
tauri-plugin-dialog = "2.2.0"
tauri-specta = { version = "2.0.0-rc.21", features = ["typescript", "derive"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }

[profile.dev]
incremental = true

[workspace]
members = ["metadata_audio"]

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
opt-level = "s"   # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Ensures debug symbols are removed. HAS TO BE FALSE DUE TO #8929
