[package]
name = "sodapop-reimagined"
version = "0.0.0"
description = "A local modern-looking music player written in Vue + Tauri"
authors = ["crackheadakira"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-shell = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-dialog = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-fs = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
audiotags = "0.5.0"
axum = "0.6.19"
tokio = { version = "1.29.1", features = ["full"] }
tower-http = { version = "0.4.3", features = ["fs", "cors"] }
dirs = "5.0.1"
rusqlite = { version = "0.31.0", features = ["bundled"] }
dotenvy = "0.15"
r2d2_sqlite = "0.24.0"
r2d2 = "0.8.10"
lazy_static = "1.4.0"
