[package]
name = "Sodapop-Reimagined"
version = "0.0.0"
description = "A modern-looking local music player written in Vue + Tauri"
authors = ["crackheadakira"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
dirs = "6.0.0"
discord-rich-presence = "0.2.5"
dotenvy = "0.15.7"
kira = "0.10.4"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
specta = "2.0.0-rc.21"
specta-typescript = "0.0.9"
souvlaki = { version = "0.8.0", default-features = false, features = [
    "use_zbus",
] }
tauri = { version = "2.2.5", features = ["protocol-asset"] }
tauri-plugin-dialog = "2.2.0"
tauri-specta = { version = "2.0.0-rc.21", features = ["typescript", "derive"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }

metadata_audio = { path = "./metadata_audio" }
db = { path = "./db", features = ["serialization"] }
lastfm = { path = "./lastfm" }
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"

[target.'cfg(windows)'.dependencies]
raw-window-handle = "0.6.2"

[profile.dev]
incremental = true

[workspace]
members = ["db", "lastfm", "metadata_audio"]

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
opt-level = "s"   # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Ensures debug symbols are removed. HAS TO BE FALSE DUE TO #8929
