[package]
name = "Sodapop-Reimagined"
version = "0.0.0"
description = "A local modern-looking music player written in Vue + Tauri"
authors = ["crackheadakira"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
anyhow = "1.0.95"
byteorder = "1.5.0"
dirs = "6.0.0"
dotenvy = "0.15.7"
kira = "0.10.2"
souvlaki = "0.8.0"

tokio = { version = "1.43.0", features = ["full"] }

rusqlite = { version = "0.32.1", features = ["bundled"] }
r2d2_sqlite = "0.25.0"
r2d2 = "0.8.10"

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.136"

raw-window-handle = "0.6.2"
tauri = { version = "2.2.3", features = ["protocol-asset"] }
tauri-plugin-dialog = "2.2.0"
tauri-plugin-fs = "2.2.0"

specta = "2.0.0-rc.21"
specta-typescript = "0.0.9"
tauri-specta = { version = "2.0.0-rc.21", features = ["typescript"] }

[lib]
name = "audio_metadata"
path = "src/metadata/lib.rs"
crate-type = ["lib", "staticlib", "cdylib"]

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
opt-level = "s"   # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = false     # Ensures debug symbols are removed. HAS TO BE FALSE DUE TO #8929
