[package]
name = "lastfm"
version = "0.0.0"
edition = "2024"

[dependencies]
md5 = "0.8.0"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
