[package]
name = "lastfm"
version = "0.0.0"
edition = "2024"

[dependencies]
md5 = "0.7.0"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
thiserror = "2.0.11"
