[package]
name = "db"
version = "0.0.0"
edition = "2024"

[dependencies]
once_cell = "1.20.3"
r2d2 = "0.8.10"
r2d2_sqlite = "0.27.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
thiserror = "2.0.11"
include_dir = "0.7.4"
common = { path = "../common", features = ["rusqlite"] }
