[package]
name = "metadata_audio"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
thiserror = "2.0.12"
logging.workspace = true

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "metadata_bench"
harness = false
